# Generated by Django 5.2.10 on 2026-01-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='external_customer_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
